name: Publish Docker image

on:
  push:
    branches: [main]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_HUB_SECRET}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@38b36773831fce8789962056bf155ba063580c34
        with:
          images: seliba/booru-bot

      - name: Build and push Docker image
        uses: docker/build-push-action@729f7f49266dec5e72fe7339273d3f7e65abacd7
        with:
          context: .
          push: true
          tags: seliba/booru-bot:latest
          labels: ${{ steps.meta.outputs.labels }}
