name: Publish Docker image

on:
  push:
    branches: [main]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@5139682d94efc37792e6b54386b5b470a68a4737
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_HUB_SECRET}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@232fc64e3a4e54539e087c5976439ea54be0959d
        with:
          images: seliba/booru-bot

      - name: Build and push Docker image
        uses: docker/build-push-action@090ca155fc9b214cbcac536c450455a0e96f52c6
        with:
          context: .
          push: true
          tags: seliba/booru-bot:latest
          labels: ${{ steps.meta.outputs.labels }}
